# Cloudflare Worker & D1 Database Configuration
name = "exemplar-learning-media"
main = "worker.js"
compatibility_date = "2026-08-01"

# Bind D1 Database (exemplar_db)
[[d1_databases]]
binding = "DB"
database_name = "exemplar_db"
database_id = "5a753e8a-3d2f-4415-b5ed-d0a59315610b"
